### ISSUE TITLE
Linear Mapping components

### ISSUE THREAD

**Issue by Abc11c** [YixiaoWang7/OptTrajDiff#2]
Hi @YixiaoWang7, Thank you for releasing the code!

I was wondering if it would be possible for you to point me to the code related to the learning of the linear mapping components or how to obtain the PCA for the agroverse dataset.

I want the Linear Mapping to be learned relative to the ego's position, heading etc

Thanks!

**Comment by YixiaoWang7** [comment]
Thank you for your interest in this research project! I have attached the code for PCA. Please note that the ground truth trajectory should be collected on your local machine, as it is a bit too large.
Thank you!

[pca_code.zip](https://github.com/user-attachments/files/17311623/pca_code.zip)
